// packages/svelte/src/Rect.svelte
<script lang="ts">
import { Rect } from '@annotacanvas/core'
import Node from './Node.svelte'
import { SHAPE_KEYS } from './keys.js'
import type { ShapeProps } from './types.js'

let { node = $bindable(), ...props }: ShapeProps = $props()
</script>

<Node nodeClass={Rect} keys={[...SHAPE_KEYS, 'width', 'height']} {props} bind:node />

// packages/angular/src/rect.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'
import { type Node, Rect } from '@annotacanvas/core'
import { AcShapeBase } from './ac-shape.base'
import { SHAPE_KEYS } from './keys'

@Component({
  selector: 'ac-rect',
  standalone: true,
  template: '',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AcRectComponent extends AcShapeBase {
  @Input() width?: number
  @Input() height?: number
  protected override readonly mirrorKeys = [...SHAPE_KEYS, 'width', 'height']
  protected override createNode(): Node {
    return new Rect(this.buildConfig() as never)
  }
}
