// packages/svelte/src/Text.svelte
<script lang="ts">
import { Text } from '@annotacanvas/core'
import Node from './Node.svelte'
import { SHAPE_KEYS } from './keys.js'
import type { ShapeProps } from './types.js'

let { node = $bindable(), ...props }: ShapeProps = $props()
</script>

<Node
  nodeClass={Text}
  keys={[...SHAPE_KEYS, 'text', 'fontSize', 'fontFamily', 'textAlign', 'textBaseline']}
  {props}
  bind:node
/>

// packages/angular/src/text.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'
import { type Node, Text } from '@annotacanvas/core'
import { AcShapeBase } from './ac-shape.base'
import { SHAPE_KEYS } from './keys'

@Component({
  selector: 'ac-text',
  standalone: true,
  template: '',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AcTextComponent extends AcShapeBase {
  @Input() text?: string
  @Input() fontSize?: number
  @Input() fontFamily?: string
  @Input() textAlign?: string
  @Input() textBaseline?: string
  protected override readonly mirrorKeys = [
    ...SHAPE_KEYS,
    'text',
    'fontSize',
    'fontFamily',
    'textAlign',
    'textBaseline',
  ]
  protected override createNode(): Node {
    return new Text(this.buildConfig() as never)
  }
}
