// packages/angular/src/line.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'
import { Line, type Node } from '@veyrajs/core'
import { AcShapeBase } from './ac-shape.base'
import { SHAPE_KEYS } from './keys'

@Component({
  selector: 'ac-line',
  standalone: true,
  template: '',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AcLineComponent extends AcShapeBase {
  @Input() points?: number[]
  @Input() closed?: boolean
  protected override readonly mirrorKeys = [...SHAPE_KEYS, 'points', 'closed']
  protected override createNode(): Node {
    return new Line(this.buildConfig() as never)
  }
}

// packages/svelte/src/Line.svelte
<script lang="ts">
import { Line } from '@veyrajs/core'
import Node from './Node.svelte'
import { SHAPE_KEYS } from './keys.js'
import type { ShapeProps } from './types.js'

let { node = $bindable(), ...props }: ShapeProps = $props()
</script>

<Node nodeClass={Line} keys={[...SHAPE_KEYS, 'points', 'closed']} {props} bind:node />
