// packages/angular/src/context.ts
import { InjectionToken } from '@angular/core'
import type { Container, History, SelectionManager, Stage } from '@annotacanvas/core'

/**
 * The context shared down the component tree via Angular's hierarchical DI. Each container
 * provides itself under this token; a child reads its parent's `container` to attach.
 */
export interface NodeContext {
  readonly stage: Stage | null
  /** The container a child attaches to (the stage for layers; a layer/group otherwise). */
  readonly container: Container | null
  readonly selection: SelectionManager | null
  readonly history: History | null
}

export const NODE_CONTEXT = new InjectionToken<NodeContext>('annotacanvas.NODE_CONTEXT')

// packages/react/src/context.ts
import type { Container, History, SelectionManager, Stage } from '@annotacanvas/core'
import { createContext, useContext } from 'react'

/** Context passed from a stage/container down to its child components. */
export interface NodeContextValue {
  stage: Stage | null
  /** The container child nodes attach to (the stage for layers; a layer/group otherwise). */
  parent: Container | null
  selection: SelectionManager | null
  history: History | null
}

export const NodeContext = createContext<NodeContextValue>({
  stage: null,
  parent: null,
  selection: null,
  history: null,
})

export function useNodeContext(): NodeContextValue {
  return useContext(NodeContext)
}
