// packages/svelte/src/Node.svelte
<script lang="ts">
import {
  Container,
  type Node,
  type SceneEvent,
  type SceneEventType,
} from '@veyrajs/core'
import { type Snippet, onMount, untrack } from 'svelte'
import { getNodeContext, setNodeContext } from './context.js'

const EVENTS: SceneEventType[] = [
  'pointerdown',
  'pointermove',
  'pointerup',
  'pointerenter',
  'pointerleave',
  'click',
  'dblclick',
  'wheel',
  'dragstart',
  'dragmove',
  'dragend',
]

/** Engine event `click` → callback prop `onclick` (Svelte's lowercase convention). */
function handlerName(type: string): string {
  return `on${type}`
}

function buildConfig(source: Record<string, unknown>, keys: string[]): Record<string, unknown> {
  const config: Record<string, unknown> = {}
  for (const key of keys) {
    if (source[key] !== undefined) config[key] = source[key]
  }
  return config
}

interface Props {
  nodeClass: new (config?: never) => Node
  keys: string[]
  props: Record<string, unknown>
  isContainer?: boolean
  node?: Node
  children?: Snippet
}

let {
  nodeClass,
  keys,
  props,
  isContainer = false,
  node = $bindable(),
  children,
}: Props = $props()

const context = getNodeContext()
// Create the node once from the initial props. `untrack` says "read the current values, don't
// re-create when they change" — the prop mirror (below) handles subsequent updates.
const instance = untrack(() => new nodeClass(buildConfig(props, keys) as never))
node = instance
const target = instance as unknown as Record<string, unknown>

// A container provides *itself* as the parent for its children (the next level of the cascade).
if (untrack(() => isContainer)) {
  setNodeContext({
    get stage() {
      return context.stage
    },
    get parent() {
      return instance as Container
    },
    get selection() {
      return context.selection
    },
    get history() {
      return context.history
    },
  })
}

// Attach to the parent once it becomes available. Reading `context.parent` (a getter over the
// provider's reactive state) tracks it, so this re-runs the moment the stage mounts.
$effect(() => {
  const parent = context.parent
  if (parent !== null && instance.parent !== parent) parent.add(instance)
})

// Mirror prop changes onto the node. The engine's guarded setters make re-applying loop-safe.
$effect(() => {
  for (const key of keys) {
    if (key === 'id') continue
    const value = props[key]
    if (value !== undefined) target[key] = value
  }
})

// Re-emit engine events as `on*` callbacks. The handler reads `props` lazily, so Svelte's
// reactive props always hand it the latest callback — no re-subscription needed.
$effect(() => {
  const handlers = EVENTS.map((type) => {
    const handler = (event: SceneEvent): void => {
      const callback = props[handlerName(type)]
      if (typeof callback === 'function') (callback as (e: SceneEvent) => void)(event)
    }
    instance.on(type, handler)
    return [type, handler] as const
  })
  return () => {
    for (const [type, handler] of handlers) instance.off(type, handler)
  }
})

onMount(() => {
  return () => instance.remove()
})
</script>

{#if isContainer}{@render children?.()}{/if}

// packages/react/src/node-component.ts
import { Container, type Node, type SceneEvent, type SceneEventType } from '@veyrajs/core'
import {
  type ForwardRefExoticComponent,
  type ReactNode,
  type RefAttributes,
  createElement,
  forwardRef,
  useContext,
  useEffect,
  useImperativeHandle,
  useMemo,
  useRef,
} from 'react'
import { NodeContext } from './context'

const COMMON_PROPS = [
  'id',
  'name',
  'x',
  'y',
  'scaleX',
  'scaleY',
  'rotation',
  'skewX',
  'skewY',
  'offsetX',
  'offsetY',
  'opacity',
  'visible',
  'listening',
]
const STYLE_PROPS = ['fill', 'stroke', 'strokeWidth', 'lineDash', 'lineCap', 'lineJoin']
const EVENTS: SceneEventType[] = [
  'pointerdown',
  'pointermove',
  'pointerup',
  'pointerenter',
  'pointerleave',
  'click',
  'dblclick',
  'wheel',
  'dragstart',
  'dragmove',
  'dragend',
]

/** Engine event `click` → React handler prop `onClick`. */
function handlerName(type: string): string {
  return `on${type.charAt(0).toUpperCase()}${type.slice(1)}`
}

export interface NodeComponentConfig {
  name: string
  NodeClass: new (config?: never) => Node
  props?: string[]
  isShape?: boolean
  isContainer?: boolean
}

export type NodeProps = Record<string, unknown> & { children?: ReactNode }

/**
 * Build a declarative React component around an engine node: create it once, attach to the
 * parent once it's available (the reactive cascade via context), mirror prop changes onto it,
 * re-emit its events as `onX` callbacks, expose it via `ref`, and remove it on unmount.
 */
export function createNodeComponent(
  config: NodeComponentConfig,
): ForwardRefExoticComponent<NodeProps & RefAttributes<Node>> {
  const propKeys = [
    ...COMMON_PROPS,
    ...(config.isShape ? STYLE_PROPS : []),
    ...(config.props ?? []),
  ]

  const Component = forwardRef<Node, NodeProps>(function NodeComponent(props, ref) {
    const context = useContext(NodeContext)
    const nodeRef = useRef<Node | null>(null)
    if (nodeRef.current === null) {
      nodeRef.current = new config.NodeClass(buildConfig(props, propKeys) as never)
    }
    const node = nodeRef.current
    const target = node as unknown as Record<string, unknown>

    useImperativeHandle(ref, () => node, [node])

    // Attach to the parent once it becomes available; detach on unmount / parent change.
    useEffect(() => {
      const parent = context.parent
      if (parent !== null && node.parent !== parent) parent.add(node)
      return () => {
        node.remove()
      }
    }, [context.parent, node])

    // Mirror prop changes onto the node every render (guarded setters → loop-safe).
    useEffect(() => {
      for (const key of propKeys) {
        if (key === 'id') continue
        const value = props[key]
        if (value !== undefined) target[key] = value
      }
    })

    // Re-emit engine events as `onX` callbacks, reading the latest props from a ref.
    const propsRef = useRef(props)
    propsRef.current = props
    useEffect(() => {
      const handlers = EVENTS.map((type) => {
        const handler = (event: SceneEvent): void => {
          const callback = propsRef.current[handlerName(type)]
          if (typeof callback === 'function') (callback as (e: SceneEvent) => void)(event)
        }
        node.on(type, handler)
        return [type, handler] as const
      })
      return () => {
        for (const [type, handler] of handlers) node.off(type, handler)
      }
    }, [node])

    // Containers provide themselves as the parent for their children.
    const childContext = useMemo(
      () => ({ ...context, parent: node instanceof Container ? node : context.parent }),
      [context, node],
    )

    if (config.isContainer) {
      return createElement(
        NodeContext.Provider,
        { value: childContext },
        props.children as ReactNode,
      )
    }
    return null
  })

  Component.displayName = config.name
  return Component
}

function buildConfig(props: Record<string, unknown>, keys: string[]): Record<string, unknown> {
  const config: Record<string, unknown> = {}
  for (const key of keys) {
    if (props[key] !== undefined) config[key] = props[key]
  }
  return config
}
